// **********************************************************************
// Parsed By TarsParser(3.0.4), Generated By tools(20200627)
// TarsParser Maintained By <TARS> and tools Maintained By <superzheng>
// Generated from "SendEmail.tars" by Server Mode
// **********************************************************************

/* tslint:disable */
/* eslint-disable */

/// <reference types="node" />
import assert = require("assert");
import * as TarsStream from "@tars/stream";
import * as TarsRpc from "@tars/rpc";

export namespace Base {
    export enum SendEmailRet {
        SM_SUCC = 0,
        SM_SYSTEM_ERROR = -1
    }

    export namespace SendEmailRet {
        export const _classname = "Base.SendEmailRet";
        export function _write(os: TarsStream.TarsOutputStream, tag: number, val: number) { return os.writeInt32(tag, val); }
        export function _read(is: TarsStream.TarsInputStream, tag: number, def?: number) { return is.readInt32(tag, true, def); }
    }


    export abstract class SendEmailImp { 
        _name!: string
        _worker!: any

        initialize(): PromiseLike<any> | void {}

        onDispatch(current: TarsRpc.TarsCurrent, funcName: string, binBuffer: TarsStream.BinBuffer) { 
            if ("__" + funcName in this) {
                return (this as any)["__" + funcName](current, binBuffer);
            } else {
                return TarsRpc.error.SERVER.FUNC_NOT_FOUND;
            }
        }

        __tars_ping(current: TarsRpc.TarsCurrent) { 
            const _ret = 0;
            if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
                const tup = new TarsStream.UniAttribute();
                tup.tupVersion = current.getRequestVersion();
                tup.writeInt32("", _ret);

                current.doResponse(tup.encode());
            } else {
                const os = new TarsStream.TarsOutputStream();
                os.writeInt32(0, _ret);

                current.doResponse(os.getBinBuffer());
            }

            return TarsRpc.error.SUCCESS;
        }

        sendEmail(current: SendEmailImp.sendEmailCurrent, uids: TarsStream.List<string>, subject: string, title: string, html: string): any { 
            assert.fail("sendEmail function not implemented");
        }

        protected static __sendEmail_responser(this: TarsRpc.TarsCurrent, _ret: number) {
            if (this.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || this.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
                const tup = new TarsStream.UniAttribute();
                tup.tupVersion = this.getRequestVersion();
                tup.writeInt32("", _ret);

                this.doResponse(tup.encode());
            } else if (this.getRequestVersion() === TarsStream.Tup.JSON_VERSION) {
                const _data_ = {
                    "tars_ret": _ret
                };

                this.doResponse(new TarsStream.BinBuffer(Buffer.from(JSON.stringify(_data_))));
            } else {
                const os = new TarsStream.TarsOutputStream();
                os.writeInt32(0, _ret);

                this.doResponse(os.getBinBuffer());
            }
        }

        protected __sendEmail(current: TarsRpc.TarsCurrent, binBuffer: TarsStream.BinBuffer) {
            let uids: TarsStream.List<string>;
            let subject: string;
            let title: string;
            let html: string;

            if (current.getRequestVersion() === TarsStream.Tup.TUP_SIMPLE || current.getRequestVersion() === TarsStream.Tup.TUP_COMPLEX) {
                const tup = new TarsStream.UniAttribute();
                tup.tupVersion = current.getRequestVersion();
                tup.decode(binBuffer);
                uids = tup.readList("uids", TarsStream.List(TarsStream.String));
                subject = tup.readString("subject");
                title = tup.readString("title");
                html = tup.readString("html");
            } else if (current.getRequestVersion() === TarsStream.Tup.JSON_VERSION) {
                const _data_ = JSON.parse(binBuffer.toNodeBuffer().toString());
                uids = _data_.uids;
                subject = _data_.subject;
                title = _data_.title;
                html = _data_.html;
            } else {
                const is = new TarsStream.TarsInputStream(binBuffer);
                uids = is.readList(1, true, TarsStream.List(TarsStream.String));
                subject = is.readString(2, true, "");
                title = is.readString(3, true, "");
                html = is.readString(4, true, "");
            }

            current.sendResponse = SendEmailImp.__sendEmail_responser;

            this.sendEmail(current, uids, subject, title, html);

            return TarsRpc.error.SUCCESS;
        }

    }

    export namespace SendEmailImp {
        export interface sendEmailCurrent extends TarsRpc.TarsCurrent {
            sendResponse(ret: number): void;
        }
    }

}


