
// **********************************************************************
// Parsed By TarsParser(3.0.2), Generated By tools(20200627)
// TarsParser Maintained By <TARS> and tools Maintained By <superzheng>
// Generated from "User.tars" by Imp Mode
// **********************************************************************

import * as TarsStream from "@tars/stream";
import * as base from "./protocol/SendEmail";
import TarsLogs from "@tars/logs";
import webConf from './webConf';
import TarsConfig from "@tars/config";
import nodemailer from "nodemailer";
export namespace Base {
    export class SendEmailImp extends base.Base.SendEmailImp {

        protected _logger = new TarsLogs("TarsRotate");
        protected _dayLogger = new TarsLogs("TarsDate");

        private _transporter: any;

        async initialize() {

            if (process.env.TARS_CONFIG) {
                const tarsConfig = new TarsConfig();

                const conf = await tarsConfig.loadConfig(`config.json`, { format: tarsConfig.FORMAT.JSON });

                this._logger.debug("initialize, in tars conf: ", conf);

                webConf.config = conf;

                this._logger.debug("initialize, in tars webConfig: ", webConf);
            }

            // await LoginService.initialize(webConf.config.dbConf);

        }

        public async sendEmail(current: base.Base.SendEmailImp.sendEmailCurrent, uids: TarsStream.List<string>, subject: string, title: string, html: string) {

            if (!this._transporter) {
                this._transporter = await nodemailer.createTransport(webConf.config.email.smtp);

                const info = await this._transporter.verify();

                this._logger.debug('sendmail verify:', info);
            }

            let u = uids.toObject();

            const info = await this._transporter.sendMail({
                from: webConf.config.email.smtp.auth.user,
                to: u,
                subject: subject,
                text: title,
                html: html,
            });

            this._logger.debug("Message sent: ", info, u);
            this._dayLogger.debug(`sendEmail|${u}|${subject}`);

            current.sendResponse(base.Base.SendEmailRet.SM_SUCC);
        }

    }
}
